Repository MystenLabs/walrus-sites, pull requests merged in 2025-02, with the labels that each got.

#377 feat: sew 25 replace node runtime with bun
  .github/workflows/codspeed.yml
  .github/workflows/portal-tests.yml
  portal/bun.lock
  portal/common/html_templates/404-page.template.html
  portal/common/html_templates/hash-mismatch.html
  portal/common/lib/http/http_error_responses.ts
  portal/common/package.json
  portal/common/tsconfig.json
  portal/common/vite.config.mts
  portal/package.json
  portal/pnpm-lock.yaml
  portal/pnpm-workspace.yaml
  portal/server/package.json
  portal/server/tsconfig.json
  portal/server/vercel.json
  portal/vercel.json
  portal/worker/README.md
  portal/worker/package.json
  portal/worker/static/404-page.template.html
  portal/worker/static/concrete.css
  portal/worker/static/fonts/AlumniSans-Bold.ttf
  portal/worker/static/fonts/InterTight-Bold.ttf
  portal/worker/static/fonts/InterTight-Medium.ttf
  portal/worker/static/hash-mismatch.html
  portal/worker/static/images/apple-touch-icon.png
  portal/worker/static/images/favicon-16x16.png
  portal/worker/static/images/favicon-32x32.png
  portal/worker/static/images/favicon.ico
  portal/worker/static/index-sw-enabled.html
  portal/worker/static/index.html
  portal/worker/static/normalize.css
  portal/worker/tsconfig.json
  portal/worker/webpack.config.common.js
Labels: enhancement

#386 feat: sew 26 amplitude integration along with web analytics
  portal/bun.lock
  portal/server/app/route.ts
  portal/server/package.json
  portal/server/src/amplitude.ts
  portal/server/src/configuration_loader.ts
  portal/server/src/utils.ts
  portal/server/src/web_analytics.ts
Labels: ops, server-portal

#389 chore: increase amplitude flushIntervalMillis to 20000
  portal/server/src/amplitude.ts
Labels: chore

#387 feat: Add a Dockerfile for Bun server
  .editorconfig
  portal/.dockerignore
  portal/docker/server/Dockerfile
  portal/package.json
  portal/server/next-env.d.ts
  portal/server/package.json
Labels: ops

#391 feat(amplitude): add props - extra.subdomain, platform, manufacturer
  portal/server/src/amplitude.ts
Labels: server-portal

#393 fix: amplitude platform value
  portal/server/src/amplitude.ts
Labels: server-portal

#394 fix: isHtmlPage should not throw exception when path is not parseable
  portal/server/src/utils.ts
Labels: server-portal

#397 feat(amplitude): track originalUrl
  portal/server/src/amplitude.ts
Labels: enhancement

#399 chore: check that each redis url db number is defined correctly
  portal/server/next-env.d.ts
  portal/server/src/configuration_loader.ts
Labels: chore

#402 feat(common): update constants to support different networks
  portal/common/lib/aggregator.ts
  portal/common/lib/constants.ts
  portal/common/lib/redirects.test.ts
  portal/common/lib/redirects.ts
  portal/common/lib/resource.test.ts
  portal/common/lib/resource.ts
  portal/common/lib/url_fetcher.ts
  portal/docker/server/Dockerfile
  portal/server/.env.example
  portal/server/app/route.ts
  portal/server/src/configuration_loader.ts
  portal/server/src/url_fetcher_factory.ts
  portal/worker/.env.example
  portal/worker/src/walrus-sites-sw.ts
  portal/worker/webpack.config.common.js
Labels: portal, common-library

#403 feat(common): remove newlines from console for compact logs
  portal/common/lib/logger.ts
Labels: common-library

#409 fix(sentry): replace @sentry/node with @sentry/bun
  portal/bun.lock
  portal/common/lib/rpc_selector.ts
  portal/server/package.json
  portal/server/src/sentry_logger.ts
Labels: bug

#401 fix: prevent 404.html override when routes exist
  portal/common/.env.test
  portal/common/lib/http/http_error_responses.ts
  portal/common/lib/routing.test.ts
  portal/common/lib/url_fetcher.ts
Labels: bug

#325 feat(site-builder): dry-run
  Cargo.lock
  c4/workspace.json
  site-builder/Cargo.toml
  site-builder/src/main.rs
  site-builder/src/publish.rs
  site-builder/src/site/manager.rs
  site-builder/src/walrus.rs
  site-builder/src/walrus/command.rs
  site-builder/src/walrus/output.rs
Labels: site-builder

#411 fix(vercel): update vercel.json to use the sp instead
  portal/vercel.json
  portal/worker/vercel.json
Labels: ops

#412 fix(sentry): ssl certificate verification on local builds require SENTRY_AUTH_TOKEN
  portal/docker/server/Dockerfile
Labels: ops

#413 fix(logs): when sentry is enabled logs should still be human readable
  portal/server/src/sentry_logger.ts
Labels: chore

#415 feat: sew 64 create an api to edit the blocklist
  portal/blocklist_api/.env.example
  portal/blocklist_api/README.md
  portal/blocklist_api/bun.lock
  portal/blocklist_api/manual_testing/ws_blocklist_api/Add subdomain.bru
  portal/blocklist_api/manual_testing/ws_blocklist_api/Delete subdomain.bru
  portal/blocklist_api/manual_testing/ws_blocklist_api/Healthcheck.bru
  portal/blocklist_api/manual_testing/ws_blocklist_api/Subdomain exists.bru
  portal/blocklist_api/manual_testing/ws_blocklist_api/bruno.json
  portal/blocklist_api/package.json
  portal/blocklist_api/src/index.ts
  portal/blocklist_api/src/redis.ts
  portal/blocklist_api/tsconfig.json
  portal/docker/blocklist_api/Dockerfile
Labels: enhancement
