Repository MystenLabs/walrus-sites, pull requests merged in 2025-03, with the labels that each got.

#424 feat(portal): sew 82 testnet portal until mainnet should not support b36 domains
  portal/common/lib/routing.test.ts
  portal/common/lib/suins.ts
  portal/common/lib/url_fetcher.ts
  portal/docker/server/Dockerfile
  portal/server/.env.example
  portal/server/app/route.ts
  portal/server/src/configuration_loader.ts
  portal/server/src/url_fetcher_factory.ts
  portal/worker/src/walrus-sites-sw.ts
  site-builder/src/publish.rs
Labels: suins

#427 docs: restructure and improve README
  README.md
Labels: documentation

#431 refactor(common): getObjectIdLink and getBlobId use URL input
  portal/common/lib/links.test.ts
  portal/common/lib/links.ts
  portal/common/vite.config.mts
  portal/server/app/route.ts
  portal/worker/src/walrus-sites-sw.ts
Labels: refactor, common-library

#435 refactor: sew 101 refactor server portal to make the framework transition
  portal/server/app/api/healthz/route.ts
  portal/server/app/route.ts
  portal/server/src/blocklist_healthcheck.ts
  portal/server/src/main.ts
Labels: refactor, server-portal

#432 feat(common): decompress chunk by chunk
  portal/common/lib/decompress_data.test.ts
  portal/common/lib/decompress_data.ts
Labels: common-library

#433 feat: sew 70 use a cookie monster inside the middleware
  portal/bun.lock
  portal/server/middleware.ts
  portal/server/package.json
  portal/server/src/cookie_monster.ts
Labels: server-portal

#436 refactor(server-portal): sew 102 replace nextrequest with request
  portal/server/app/route.ts
  portal/server/src/amplitude.ts
  portal/server/src/main.ts
  portal/server/src/utils.ts
  portal/server/src/web_analytics.ts
Labels: server-portal

#437 feat(server-portal): sew 73 migrate from nextjs to another simpler framework
  portal/bun.lock
  portal/common/lib/http/http_error_responses.ts
  portal/common/package.json
  portal/docker/server/Dockerfile
  portal/package.json
  portal/server/app/api/healthz/route.ts
  portal/server/app/layout.tsx
  portal/server/app/route.ts
  portal/server/index.ts
  portal/server/middleware.ts
  portal/server/next-env.d.ts
  portal/server/next.config.mjs
  portal/server/package.json
  portal/server/src/main.ts
  portal/server/tsconfig.json
  portal/server/vercel.json
Labels: enhancement, server-portal, epic

#438 fix: sp-tnet should not define output dir
  portal/server/vercel.json
Labels: bug

#439 chore: remove debug log
  portal/common/lib/links.ts
Labels: chore

#441 chore: example LANDING_PAGE_OID_B36 should be same as prod
  portal/server/.env.example
Labels: chore

#444 fix(server-portal): bump Dockerfile Bun to 1.2.5
  portal/docker/server/Dockerfile
Labels: bug

#442 chore: use a special __wal__ path
  portal/bun.lock
  portal/server/index.ts
Labels: chore

#449 feat(server-portal): do not allow subdomain access when BRING_YOUR_OWN_DOMAIN is true
  portal/common/lib/http/http_error_responses.ts
  portal/server/src/configuration_loader.ts
  portal/server/src/main.ts
Labels: server-portal

#454 fix: bump bun.lock to align with grafana changes
  portal/bun.lock
Labels: chore

#453 fix: Return home to subdomain
  portal/common/html_templates/404-page.template.html
  portal/common/html_templates/globe_big.png
Labels: landing-page

#445 chore: remove walrus-sites-sw.js from server portal
  portal/server/index.ts
  portal/server/public/walrus-sites-sw.js
Labels: chore, server-portal, service-worker

#450 chore: seint 1020 create example env files per network
  portal/server/.env.mainnet.example
  portal/server/.env.testnet.example
  portal/worker/.env.mainnet.example
  portal/worker/.env.testnet.example
Labels: chore

#459 chore: replace walrus.site with wal.app
  .github/ISSUE_TEMPLATE/code-bug.yaml
  README.md
  c4/README.md
  examples/snake/ws-resources.json
  move/walrus_site/tests/site_tests.move
  portal/common/html_templates/hash-mismatch.html
  portal/common/lib/domain_parsing.test.ts
  portal/common/lib/domain_parsing.ts
  portal/common/lib/redirects.test.ts
  portal/server/src/cookie_monster.ts
  portal/worker/404.html
  portal/worker/index.html
  portal/worker/static/404-page.template.html
  portal/worker/static/hash-mismatch.html
  portal/worker/static/index-sw-enabled.html
  portal/worker/static/index.html
  site-builder/src/main.rs
  site-builder/src/publish.rs
  site-builder/src/site/config.rs
  sites-config.yaml
Labels: chore

#462 chore: sew 113 update the .env.example configuration files and Dockerfile
  portal/docker/server/Dockerfile
  portal/server/.env.mainnet.example
  portal/server/.env.testnet.example
  portal/worker/.env.mainnet.example
  portal/worker/.env.testnet.example
Labels: chore

#456 feat!: mainnet launch updates
  .github/ISSUE_TEMPLATE/code-bug.yaml
  .github/workflows/move-tests.yml
  README.md
  c4/README.md
  examples/snake/ws-resources.json
  move/walrus_site/.prettierrc
  move/walrus_site/Move.lock
  move/walrus_site/sources/events.move
  move/walrus_site/sources/metadata.move
  move/walrus_site/sources/site.move
  move/walrus_site/tests/site_tests.move
  portal/common/html_templates/hash-mismatch.html
  portal/common/lib/domain_parsing.test.ts
  portal/common/lib/domain_parsing.ts
  portal/common/lib/redirects.test.ts
  portal/docker/server/Dockerfile
  portal/server/.env.mainnet.example
  portal/server/.env.testnet.example
  portal/server/index.ts
  portal/server/public/walrus-sites-sw.js
  portal/server/src/cookie_monster.ts
  portal/worker/.env.example
  portal/worker/.env.mainnet.example
  portal/worker/.env.testnet.example
  portal/worker/404.html
  portal/worker/index.html
  portal/worker/static/404-page.template.html
  portal/worker/static/hash-mismatch.html
  portal/worker/static/index-sw-enabled.html
  portal/worker/static/index.html
  site-builder/src/display.rs
  site-builder/src/main.rs
  site-builder/src/publish.rs
  site-builder/src/site/builder.rs
  site-builder/src/site/config.rs
  site-builder/src/site/manager.rs
  site-builder/src/site/resource.rs
  site-builder/src/types.rs
  site-builder/src/walrus.rs
  site-builder/src/walrus/command.rs
  site-builder/src/walrus/output.rs
  sites-config.yaml
Labels: enhancement, epic

#466 docs(README): fix stake site url
  README.md
Labels: documentation

#467 feat(suins): only resolve when "link to walrus site" is used
  portal/common/lib/suins.test.ts
  portal/common/lib/suins.ts
Labels: suins
